Modernize qualtrics-survey xblock
Stanford-Online/xblock-qualtrics-survey pull request #12
Opened 2019-05-15 23:05 UTC by stvstnfrd

following changes made to image-modal xblock

2019-05-15 23:06 UTC, stvstnfrd commented
The `README` still needs a little updating, but everything else should be good to go.

Test with:
- `make`
- `make test && make runserver`

2019-06-21 22:14 UTC, stvstnfrd reviewed
I'll tweak the README a little prior to merge (mostly just needs screenshots and walkthrough videos), but the code is ready and contains the latest updates from the `image-modal`.

@caesar2164 @dcadams Please review.

2019-06-21 22:14 UTC, stvstnfrd commented on README.rst
> +    xblock-qualtrics-survey
TODO: Publish this to PyPI.

2019-06-21 22:48 UTC, stvstnfrd commented
Actually, I take that back; I missed a change or two; please hold off.

2019-06-24 18:55 UTC, stvstnfrd commented
@caesar2164 @dcadams Okay, ready for review, for real ;)

2019-06-26 22:15 UTC, caesar2164 requested changes
First pass with obvious stuff.

2019-06-26 22:15 UTC, caesar2164 commented on .gitignore
> +package-lock.json
Do we need to add `.dockerignore` here as well?

2019-06-26 22:15 UTC, caesar2164 commented on Dockerfile
> +FROM stvstnfrd/workbench:latest
Shouldn't this be changed for our master branch?

2019-06-26 22:15 UTC, caesar2164 commented on Makefile
> +.PHONY: runserver
works!

2019-06-26 22:15 UTC, caesar2164 commented on Makefile
>  .PHONY: clean
works!

2019-06-26 22:15 UTC, caesar2164 commented on Makefile
>  .PHONY: test
works!

2019-06-26 22:15 UTC, caesar2164 commented on qualtricssurvey/public/view.css
> +  /* color: white;*/
why not just deleting this?

2019-06-26 22:15 UTC, caesar2164 commented on qualtricssurvey/public/view.less
> +        /* color: white;*/
again, why commenting this line?

2019-06-26 22:15 UTC, caesar2164 commented on qualtricssurvey/templates/view.html
> +        >{{link_text}}</a>
Closing the `a` tag on this line makes it look weird. Any other way we can do this?

2019-07-04 00:13 UTC, stvstnfrd commented on .gitignore
> +package-lock.json
No, I'm not sure why we'd want to ignore changes to the `.dockerignore` file...?

2019-07-04 00:13 UTC, stvstnfrd commented on qualtricssurvey/public/view.css
> +  /* color: white;*/
This is the compiled file, so I'll resolve this thread and respond to the `.less` file.

2019-07-04 00:13 UTC, stvstnfrd commented on qualtricssurvey/templates/view.html
> +        >{{link_text}}</a>
Eh, we're actually closing it on the same line that we're opening it.

Splitting it up maybe looks weirder?
```
        <a
          class="button primary-button qualtrics-button"
          href="https://{{your_university}}.qualtrics.com/jfe/form/{{survey_id}}{{user_id_string}}"
          target="_blank"
        >
          {{link_text}}
        </a>
```

Does that work?

2019-07-04 00:13 UTC, stvstnfrd commented on Dockerfile
> +FROM stvstnfrd/workbench:latest
This is just a stop-gap solution.

Ultimately, we'll use a container image from edx,
but we're still waiting for a few more changes to land upstream.

2019-07-04 00:13 UTC, stvstnfrd commented on qualtricssurvey/public/view.less
> +        /* color: white;*/
Removed in new commit.

2019-07-08 22:27 UTC, caesar2164 commented on .gitignore
> +package-lock.json
I guess that's true. I was just thinking that dot files are usually not for git to look at...

2019-07-08 22:28 UTC, caesar2164 commented on qualtricssurvey/public/view.less
> +        /* color: white;*/
thanks.

2019-07-08 22:28 UTC, caesar2164 commented on qualtricssurvey/templates/view.html
> +        >{{link_text}}</a>
Yes, I like that better. that makes it formatted just like tags that don't have lots of attributes.

2019-07-08 22:30 UTC, caesar2164 submitted a review, later dismissed
Nice, thanks for the changes!

2019-07-09 21:28 UTC, stvstnfrd commented
@caesar2164 README updated and commits squashed.

@mondiaz The documentation can be previewed here:
- https://github.com/Stanford-Online/xblock-qualtrics-survey/blob/modernize/README.rst

2019-07-09 22:13 UTC, mondiaz commented
@stvstnfrd Thanks for tagging me. I checked the documentation you linked to, and had a few notes:

1. The image for image-cms-add is broken (just displays a broken image icon).
2. For the "a" parameter name for userid to work, we (Kathy, really) sets up embedded data in the Qualtrics surveys to pass that value through to the Qualtrics survey reports. 
3. We don't seem to need to add any name to the Advanced Module List for the qualtrics survey xblock to work anymore. 

![Screen Shot 2019-07-09 at 3 04 33 PM](https://user-images.githubusercontent.com/7118996/60926317-fbfe1580-a25a-11e9-8505-f246365ce6fc.png)

2019-07-10 19:55 UTC, stvstnfrd commented
@mondiaz 

> 1. The image for image-cms-add is broken (just displays a broken image icon).

Fixed! Nice catch.

 
> 3. We don't seem to need to add any name to the Advanced Module List for the qualtrics survey xblock to work anymore.

Yeah, that step is optional on Lagunita, but required on any other instance (edx.org, opencraft, etc.).
We have an extra setting `XBLOCKS_ALWAYS_IN_STUDIO` that allows us to omit that for common XBlocks on our site, but I want the docs to be thorough for community members. It shouldn't hurt to add though :)


> 2. For the "a" parameter name for userid to work, we (Kathy, really) set up embedded data in the Qualtrics surveys to pass that value through to the Qualtrics survey reports.

Can we chat F2F about this?

2019-07-10 22:55 UTC, stvstnfrd commented
@mondiaz @caesar2164 Changes pushed.

2019-07-11 00:02 UTC, mondiaz commented
@stvstnfrd lgtm, thanks!

2019-07-11 19:50 UTC, caesar2164 approved these changes

2019-07-11 20:03 UTC, merged