Change qualtrics url to accomodate their change.
Stanford-Online/xblock-qualtrics-survey pull request #5
Opened 2017-04-13 23:18 UTC by dcadams

and fix the broken tests.

2017-04-13 23:22 UTC, dcadams commented
@stvstnfrd

2017-04-14 22:53 UTC, stvstnfrd requested changes

2017-04-14 22:53 UTC, stvstnfrd commented on qualtricssurvey/qualtricssurvey.py
> +        default=_('stanforduniversity'),
I think we actually _don't_ want this marked for translation, right? Isn't this like an account name?

2017-04-14 22:53 UTC, stvstnfrd commented on qualtricssurvey/tests.py
> +            'href="https://stanforduniversity.qualtrics.com/jfe/form/Enter '
Nit per f2f: We may want to stick the base part of the URL here into a variable/constant.

2017-04-17 20:16 UTC, dcadams commented on qualtricssurvey/tests.py
> +            'href="https://stanforduniversity.qualtrics.com/jfe/form/Enter '
If another test gets added I'll change it.

2017-04-18 18:16 UTC, stvstnfrd commented on qualtricssurvey/qualtricssurvey.py
> +        default= 'stanforduniversity',
PEP8 violation; no space between `=` and `kwargs`.

2017-04-18 18:16 UTC, stvstnfrd commented
@dcadams Just the one PEP8 violation, otherwise lgtm.

2017-04-18 18:19 UTC, stvstnfrd approved these changes

2017-04-18 23:07 UTC, merged