Make message editable
Stanford-Online/xblock-qualtrics-survey pull request #7
Opened 2017-07-18 17:11 UTC by jspayd

Also replaces private/view.html with the more recent public/view.html and updates public (grunt generated/copied) files.
@stvstnfrd @caseylitton

2017-07-18 18:30 UTC, caesar2164 commented
@jspayd, could the additions of the css and js `.min` and `.min.map` files be split out into a separate commit?

2017-07-18 18:32 UTC, caesar2164 commented
hmm, are those files supposed to be added in the Gruntfile PR?

2017-07-18 18:38 UTC, dcadams commented
Could you write a unit test for this?

2017-07-18 20:24 UTC, caseylitton commented
@jspayd Per @dcadams comment, There should be a similar test in free text response.  One that checks the student view context for specific keys.

2017-07-18 20:26 UTC, caseylitton commented
@caesar2164 It might be better to merge the two PRs into one.  First commit is fix the grunt file and add the missing min files.  Subsequent commits are the feature update.

https://github.com/Stanford-Online/xblock-qualtrics-survey/pull/6

2017-07-18 20:58 UTC, jspayd commented
@caesar2164 Those files were generated by Grunt and get updated any time you make changes to the source files (in the private folder). I didn't actually make any changes to the JS and Less files. I think someone else had previously made changes to the xblock by modifying the public files (rather than modifying the private files and getting Grunt to minify them). That should all be fixed now, but I could move the .min files to the Gruntfile commit if that would make more sense (since it's really only view.html and qualtricssurvey.py that I directly modified here.)

2017-07-18 21:08 UTC, jspayd commented
@dcadams Working on it now.

2017-07-18 23:30 UTC, jspayd commented
I added tests. What's the consensus on what PR the `.min` and `.min.map` files should be in? @dcadams @caesar2164 @caseylitton

2017-07-19 15:48 UTC, dcadams commented
Actually, I'd put them in their own commit in this PR.

2017-07-19 16:39 UTC, caesar2164 commented
@jspayd you did make changes to the JS and LESS, in the Grunt PR... :)
That's why I'm saying those changes should go there.

2017-07-19 17:43 UTC, jspayd commented
The changes I made to the JS and LESS files in the Grunt PR were actually just copying them from public into private (since they weren't in private already), but I think the `.min` and `.min.map` files were changed by Grunt because of that. I'll move these changes to their own commit in the Grunt PR.

2017-07-19 18:20 UTC, stvstnfrd commented
I'm tagged, but I defer to other reviewers here.

2017-07-20 20:20 UTC, caseylitton commented
@jspayd @caesar2164 I tested the grunt files PR.  https://github.com/Stanford-Online/xblock-qualtrics-survey/pull/6

Those files should be present in the other PR.  So they should not be newly added here.  

All the files will be rebuilt and change however under certain circumstances.  For example, if an html change is made the js, css, min, map whatever will be rewritten.  The whole public file will usually be different.  But the files should not be new.

2017-07-24 18:33 UTC, caesar2164 requested changes

2017-07-24 18:33 UTC, caesar2164 commented on qualtricssurvey/tests.py
> +        self.assertIn(message, fragment.content)
There probably should be a specific test for the editable message. Like testing to make sure if you change the message it gets changed in the xBlock output?

2017-07-24 20:31 UTC, jspayd commented
@caesar2164 @caseylitton I added the test @caesar2164 requested.

2017-07-24 21:02 UTC, caesar2164 commented
test this please

2017-07-24 21:04 UTC, caesar2164 approved these changes
nice!

2017-07-25 18:02 UTC, caseylitton commented
+1,   Squash your commits and then add a revision commit.  

Do that similar to one Giulio just did for free text.  https://github.com/Stanford-Online/xblock-free-text-response/pull/20

2017-07-25 18:17 UTC, jspayd commented
@caseylitton Done!

2017-07-25 19:32 UTC, merged